name: ShieldGenerator
version: '1.0-SNAPSHOT'
main: winlyps.shieldGenerator.ShieldGenerator
api-version: '1.20'
authors: [ Winlyps ]
commands:
  shieldgn:
    description: Generates a specified number of custom shields.
    usage: /shieldgn <NumberOfGeneratedShieldsMax36>